# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssu" do
  name "ssu"
  desc "Smart Submodule Updater - intelligent git submodule management"
  homepage "https://github.com/pxpxltd/ssu"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssu"

  on_macos do
    on_intel do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_darwin_amd64.tar.gz"
      sha256 "98b44668745234e18fb7bfd6d9956f2e011509e383013620168b89a00b8e212b"
    end
    on_arm do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_darwin_arm64.tar.gz"
      sha256 "6d6185f43dd78461eb1ec4a29172af6ed8407946982205171c82f565e07cdb21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_linux_amd64.tar.gz"
      sha256 "7bb127daa85d6465f3cc43f9e0323ff21c835cf4de6f3b56fbf6ca3b99d1c386"
    end
    on_arm do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_linux_arm64.tar.gz"
      sha256 "e06e9fb985e3371902e3c336634372004ba61f70e1a6c1102be3c53ce876332f"
    end
  end

  # No zap stanza required
end
