# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssu" do
  name "ssu"
  desc "Smart Submodule Updater - intelligent git submodule management"
  homepage "https://github.com/pxpxltd/ssu"
  version "1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssu"

  on_macos do
    on_intel do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_darwin_amd64.tar.gz"
      sha256 "6c595002b687ed74467d1d909f795284132ca78381f81e2b8f090d0b71f124e7"
    end
    on_arm do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_darwin_arm64.tar.gz"
      sha256 "99e25a15ecc203376a9db6df06f23fc6ad749cecbe7a510206595315c8061e60"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_linux_amd64.tar.gz"
      sha256 "0732a3b9de84735bd67b807a4cba6620db91b55aac6b2f9d522f432a5d327f5e"
    end
    on_arm do
      url "https://github.com/pxpxltd/ssu/releases/download/v#{version}/ssu_#{version}_linux_arm64.tar.gz"
      sha256 "f2b25c79d2244c853c05d7f86770874a22a8c98a71bd82ffed2cb2cbf086c12c"
    end
  end

  # No zap stanza required
end
